In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [11]:
df = pd.read_pickle("../assets/data/kepler_data.pkl")

In [12]:
df.head(10)

,index,period,period_err,bjd0,bjd0_err,morph,GLon,GLat,kmag,Teff,SC,time,flux,flux_err,n_points
KIC,,,,,,,,,,,,,,,
3863594,0,0.053268,0.000000e+00,55000.000000,0.004327,0.79,-1.0000,-1.0000,-1.000,-1.0,False,"[120.53895485026442, 120.55938947320828, 120.5...","[1.0027486085891724, 0.9967120885848999, 0.999...","[9.64640494203195e-05, 9.793051140150055e-05, ...",52286
10417986,1,0.073731,0.000000e+00,55000.027476,0.004231,0.99,81.0390,11.0820,9.128,-1.0,True,"[120.53855550513981, 120.55898988617264, 120.5...","[0.999791145324707, 0.9999734163284302, 0.9995...","[1.373476243315963e-05, 1.3659494470630307e-05...",52200
8912468,2,0.094838,0.000000e+00,54953.576945,0.005326,0.98,80.1095,7.8882,11.751,6194.0,False,"[120.53837293142715, 120.55880740127031, 120.5...","[0.9991673827171326, 0.9996739625930786, 0.995...","[5.4617426940239966e-05, 5.44519534741994e-05,...",65266
8758716,3,0.107205,0.000000e+00,54953.672989,0.006197,1.00,77.7478,11.6565,13.531,-1.0,False,"[120.53883156277152, 120.55926600434032, 120.5...","[1.0111474990844727, 0.9915452003479004, 1.001...","[0.00011227018694626167, 0.0001110159646486863...",65262
10855535,4,0.112782,0.000000e+00,54964.629315,0.006374,0.99,79.3949,15.9212,13.870,7555.0,False,"[131.51221361904754, 131.5326480107833, 131.55...","[0.9962518215179443, 1.0047160387039185, 1.005...","[0.00015937240095809102, 0.0001598708040546625...",64793
9472174,5,0.125765,1.000000e-07,54953.643178,0.018318,0.78,79.0187,11.6745,12.264,10645.0,True,"[120.53873908418609, 120.55917349758238, 120.5...","[0.9766239523887634, 0.9745587706565857, 1.014...","[6.300036329776049e-05, 6.46721528028138e-05, ...",65262
9612468,6,0.133471,1.000000e-07,54953.603803,0.007796,0.99,81.0112,8.5285,11.531,7202.0,False,"[120.53835217891174, 120.55878661484894, 120.5...","[0.999556303024292, 0.999701201915741, 1.00001...","[4.825793803320266e-05, 4.807007280760445e-05,...",65266
6613627,7,0.150800,1.000000e-07,55115.344848,0.008552,0.98,75.1606,10.2517,12.548,7090.0,False,"[120.53893169508228, 120.55936622250738, 120.5...","[0.9986772537231445, 0.9994301199913025, 0.997...","[6.944619963178411e-05, 6.992976705078036e-05,...",65262
5302006,8,0.151171,1.000000e-07,54980.509040,0.007895,0.97,75.3495,6.6449,15.050,6536.0,False,"[131.512027738936, 131.53246243730973, 131.552...","[0.9980388283729553, 1.000171184539795, 0.9940...","[0.0003836112155113369, 0.00038473118911497295...",64797
9898401,9,0.152774,1.000000e-07,54964.733972,0.008810,0.99,79.6654,11.8375,12.073,7376.0,False,"[131.51197270999546, 131.53240720440954, 131.5...","[0.999788761138916, 1.0012784004211426, 1.0014...","[5.6896758906077594e-05, 5.6929642596514896e-0...",64793

In [13]:
df.index.name

'KIC'

In [14]:
df = df.reset_index()

In [ ]:
df

,KIC,index,period,period_err,bjd0,bjd0_err,morph,GLon,GLat,kmag,Teff,SC,time,flux,flux_err,n_points
0,3863594,0,0.053268,0.0,55000.000000,0.004327,0.79,-1.0000,-1.0000,-1.000,-1.0,False,"[120.53895485026442, 120.55938947320828, 120.5...","[1.0027486085891724, 0.9967120885848999, 0.999...","[9.64640494203195e-05, 9.793051140150055e-05, ...",52286
1,10417986,1,0.073731,0.0,55000.027476,0.004231,0.99,81.0390,11.0820,9.128,-1.0,True,"[120.53855550513981, 120.55898988617264, 120.5...","[0.999791145324707, 0.9999734163284302, 0.9995...","[1.373476243315963e-05, 1.3659494470630307e-05...",52200
2,8912468,2,0.094838,0.0,54953.576945,0.005326,0.98,80.1095,7.8882,11.751,6194.0,False,"[120.53837293142715, 120.55880740127031, 120.5...","[0.9991673827171326, 0.9996739625930786, 0.995...","[5.4617426940239966e-05, 5.44519534741994e-05,...",65266
3,8758716,3,0.107205,0.0,54953.672989,0.006197,1.00,77.7478,11.6565,13.531,-1.0,False,"[120.53883156277152, 120.55926600434032, 120.5...","[1.0111474990844727, 0.9915452003479004, 1.001...","[0.00011227018694626167, 0.0001110159646486863...",65262
4,10855535,4,0.112782,0.0,54964.629315,0.006374,0.99,79.3949,15.9212,13.870,7555.0,False,"[131.51221361904754, 131.5326480107833, 131.55...","[0.9962518215179443, 1.0047160387039185, 1.005...","[0.00015937240095809102, 0.0001598708040546625...",64793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,9408440,2915,989.985000,-1.0,55346.365980,0.096130,0.00,78.5607,12.2615,13.199,5688.0,False,"[120.53881482224824, 120.55924923285056, 120.5...","[1.0003937482833862, 1.0000361204147339, 1.000...","[0.00010846254008356482, 0.0001084753821487538...",65266
2916,8054233,2916,1058.000000,-1.0,54751.806288,0.968052,0.03,78.6142,7.7321,11.783,4733.0,False,"[120.53847295136802, 120.55890745798388, 120.5...","[0.9990968108177185, 0.9993742108345032, 0.999...","[5.2870946092298254e-05, 5.34793252882082e-05,...",56339
2917,7672940,2917,1064.270000,-1.0,54977.092960,0.089646,0.00,74.5296,14.6136,12.328,-1.0,False,"[120.53926443521777, 120.55969887806714, 120.5...","[0.9998093247413635, 0.9997530579566956, 0.999...","[5.69680159969721e-05, 5.723865979234688e-05, ...",65261
2918,11961695,2918,1082.815000,-1.0,54871.395674,0.211754,0.02,81.8628,15.9404,13.718,5768.0,False,"[131.51204017500277, 131.53247452308278, 131.5...","[0.9999439716339111, 1.000364065170288, 0.9997...","[0.00016608364239800721, 0.0001661751302890479...",64796
2919,4360072,2919,1087.300000,-1.0,55165.611684,1.147790,0.05,71.5008,11.7046,11.159,4950.0,False,"[120.53930122082966, 120.55973579010606, 120.5...","[1.0007842779159546, 1.000826358795166, 1.0007...","[3.566154191503301e-05, 3.6531317164190114e-05...",56337

---

In [23]:
def plotLightCurve(df, kic, with_error=True):
    """
    Plot the light curve for a given KIC from a DataFrame.
    """
    row = df[df["Index"] == kic]
    
    if row.empty:
        raise ValueError(f"KIC {kic} not found in DataFrame.")
    
    row = row.iloc[0]
    
    t = row["time"]
    f = row["flux"]
    e = row.get("flux_err", None)

    # Plot
    plt.figure(figsize=(20, 5))
    
    if with_error and e is not None:
        plt.errorbar(t, f, yerr=e, fmt='-', linewidth=1)
    else:
        plt.plot(t, f, linewidth=1)
    
    plt.xlabel("Time")
    plt.ylabel(r"Normalized Flux (e$^{-}$ s$^{-1}$)")
    plt.title(f"KIC {kic} Light Curve")
    plt.show()

In [24]:
def sampleRandomKEB(df):
    idx = np.random.randint(0, len(df))
    kic = int(df.loc[idx]['KIC'])

    return kic

---

In [25]:
sampleKIC = df.sample(n=1).index[0]
sampleKIC

49

In [26]:
plotLightCurve(df, kic=sampleKIC)

KeyError: 'Index'

In [ ]:
df

,index,period,period_err,bjd0,bjd0_err,morph,GLon,GLat,kmag,Teff,SC,time,flux,flux_err,n_points
KIC,,,,,,,,,,,,,,,
3863594,0,0.053268,0.0,55000.000000,0.004327,0.79,-1.0000,-1.0000,-1.000,-1.0,False,"[120.53895485026442, 120.55938947320828, 120.5...","[1.0027486085891724, 0.9967120885848999, 0.999...","[9.64640494203195e-05, 9.793051140150055e-05, ...",52286
10417986,1,0.073731,0.0,55000.027476,0.004231,0.99,81.0390,11.0820,9.128,-1.0,True,"[120.53855550513981, 120.55898988617264, 120.5...","[0.999791145324707, 0.9999734163284302, 0.9995...","[1.373476243315963e-05, 1.3659494470630307e-05...",52200
8912468,2,0.094838,0.0,54953.576945,0.005326,0.98,80.1095,7.8882,11.751,6194.0,False,"[120.53837293142715, 120.55880740127031, 120.5...","[0.9991673827171326, 0.9996739625930786, 0.995...","[5.4617426940239966e-05, 5.44519534741994e-05,...",65266
8758716,3,0.107205,0.0,54953.672989,0.006197,1.00,77.7478,11.6565,13.531,-1.0,False,"[120.53883156277152, 120.55926600434032, 120.5...","[1.0111474990844727, 0.9915452003479004, 1.001...","[0.00011227018694626167, 0.0001110159646486863...",65262
10855535,4,0.112782,0.0,54964.629315,0.006374,0.99,79.3949,15.9212,13.870,7555.0,False,"[131.51221361904754, 131.5326480107833, 131.55...","[0.9962518215179443, 1.0047160387039185, 1.005...","[0.00015937240095809102, 0.0001598708040546625...",64793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9408440,2915,989.985000,-1.0,55346.365980,0.096130,0.00,78.5607,12.2615,13.199,5688.0,False,"[120.53881482224824, 120.55924923285056, 120.5...","[1.0003937482833862, 1.0000361204147339, 1.000...","[0.00010846254008356482, 0.0001084753821487538...",65266
8054233,2916,1058.000000,-1.0,54751.806288,0.968052,0.03,78.6142,7.7321,11.783,4733.0,False,"[120.53847295136802, 120.55890745798388, 120.5...","[0.9990968108177185, 0.9993742108345032, 0.999...","[5.2870946092298254e-05, 5.34793252882082e-05,...",56339
7672940,2917,1064.270000,-1.0,54977.092960,0.089646,0.00,74.5296,14.6136,12.328,-1.0,False,"[120.53926443521777, 120.55969887806714, 120.5...","[0.9998093247413635, 0.9997530579566956, 0.999...","[5.69680159969721e-05, 5.723865979234688e-05, ...",65261
11961695,2918,1082.815000,-1.0,54871.395674,0.211754,0.02,81.8628,15.9404,13.718,5768.0,False,"[131.51204017500277, 131.53247452308278, 131.5...","[0.9999439716339111, 1.000364065170288, 0.9997...","[0.00016608364239800721, 0.0001661751302890479...",64796
4360072,2919,1087.300000,-1.0,55165.611684,1.147790,0.05,71.5008,11.7046,11.159,4950.0,False,"[120.53930122082966, 120.55973579010606, 120.5...","[1.0007842779159546, 1.000826358795166, 1.0007...","[3.566154191503301e-05, 3.6531317164190114e-05...",56337